### ISSUE TITLE
[User Story] - Entity checklist for filters

### ISSUE THREAD

**Issue by FilipeCovas** [setup-world/setupworld-roadmap#2]
### Description
I, as a user, want to be able to see a list of elements in the form of pagination with "see more" of a specific entity. I will also be able to search for a specific element that will be added to the existing list.

### Acceptance Criteria

- [x] A guest user can view and select from the list.
- [x] A guest user can search for an element in the list.
- [x] A guest user can click on the "see more" button and the next elements of the list will be displayed.

### Constraints
---

### References
 1. UI Example: https://dribbble.com/shots/15899953-Filtering-Component-Table-Exploration
